project:
  type: book
  output-dir: docs

highlight-style: github

book:
  title: "Business Analytics Workshop"
  author: "Yuan Tian"
  date: "10/13/2025"
  chapters:
    - index.qmd
    - bash.qmd
    - python-terminal.qmd
    - streamlit.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
#      - sandstone
      - brite
#      - minty
#      - flatly
#      - brand
    toc: true
    toc-depth: 3
    number-sections: true
    code-fold: true
    code-summary: "Click to expand/collapse"
  pdf:
    documentclass: scrreprt



